Transitioned /common to TypeScript
nathanrydel/react-jobly-v2 pull request #26
Opened 2024-04-01 17:50 UTC by SarthakSanjay

Fixes #7

2024-04-02 18:40 UTC, evengene commented
hey @SarthakSanjay, thank you for contributing,
Could you please in the future name your branch according to the issue name?  
For example, in this case `7-transitioning-common-to-ts`
This approach keeps PR merge history clean and makes it easy to navigate through them.
thanks!

2024-04-02 18:50 UTC, evengene requested changes

2024-04-02 18:50 UTC, evengene commented on frontend/src/common/Alert.tsx
> +const Alert: React.FC<AlertProps> = ({ type = "danger", messages = [] }) => {
you can import `FC` directly from react, like this:
```
import type { FC } from 'react';

const Alert: FC<AlertProps>
...
```

2024-04-02 18:50 UTC, evengene commented on frontend/src/common/SearchForm.tsx
> +interface SearchFormProps{
`...Props { ` - formatting

2024-04-02 18:50 UTC, evengene commented on frontend/src/common/SearchForm.tsx
> +const SearchForm: React.FC<SearchFormProps> = ({ searchFor }) => {
same as above, you can import just  `FC`

2024-04-02 18:50 UTC, evengene commented on frontend/src/common/SearchForm.tsx
> +  const handleSubmit = (evt:React.FormEvent):void => {
same as above

2024-04-02 18:50 UTC, evengene commented on frontend/src/common/SearchForm.tsx
> +  const handleChange = (evt:React.ChangeEvent<HTMLInputElement>):void => {
same as above

2024-04-03 07:50 UTC, SarthakSanjay commented
@evengene thanks for the review

2024-04-07 22:13 UTC, nathanrydel approved these changes

2024-04-07 22:13 UTC, merged